from django.urls import  path,include
from petcare import views

urlpatterns = [
    path('login/',views.login),
    path('loginpst/',views.loginpst),
    path('adminhome/',views.adminhome),
    path('userhome/',views.userhome),
    path('shophome/',views.shophome),
    path('dochome/',views.dochome),
    path('admin_changepass/',views.admin_changepass),
    path('admin_changepass_post/',views.admin_changepass_post),
    path('usersignup/',views.usersignup),
    path('doctorsignup/',views.doctorsignup),
    path('shopsignup/',views.shopsignup),
    path('userpost/',views.userpost),
    path('userview/',views.userview),
    path('useruserview/',views.useruserview),
    path('useredit/<str:id>',views.useredit),
    path('usereit/',views.usereit),
    path('shoppost/',views.shoppost),
    path('shopview/',views.shopview),
    path('shopshopview/', views.shopshopview),

    path('shopedit/<str:id>', views.shopedit),
    path('shopeit/',views.shopeit),
    path('doctorpost/',views.doctorpost),
    path('docview/',views.doctorview),
    path('docdocview/', views.docdocview),

    path('docedit/<str:id>', views.docedit),
    path('doctoredit/',views.doctoredit),
    path('category/',views.catgory),
    path('catepost/',views.catepost),
    path('cateview/',views.cateview),
    path('cateedit/<str:id>',views.cateedit),
    path('cateedp/',views.catedp),
    path('product/',views.product),
    path('productpost/',views.productpost),
    path('productview/',views.productview),
    path('productcart/<str:id>',views.product_cart),
    path('cartpost/',views.cartpost),
    path('viewcart/',views.viewcart),
    path('deletecart/<id>',views.user_delete_cart),

    path('userviewproduct/',views.user_productview),
    path('producted/<id>',views.producted),
    path('adviewshop/',views.adshopview),
    path('adminshopapp/',views.adshopapproved),
    path('adminshopreject/',views.adshopreject),
    path('admin_approve_shop/<id>',views.admin_approve_shop),
    path('admin_reject_shop/<id>',views.admin_reject_shop),
    path('adminviewdoc/',views.adviewdoc),
    path('adminappdoc/',views.addocapproved),
    path('adminrejdoc/',views.addocreject),
    path('admin_approve_doctor/<id>',views.admin_approve_doc),
    path('admin_reject_doctor/<id>',views.admin_reject_doc),
    path('deliveryhome/', views.deliveryhome),

    path('delivery/',views.delivery),
    path('deleverypost/',views.deliverypost),
    path('complaint/',views.complain),
    path('complaintpost/',views.complaintpost),
    path('viewcomp/',views.adminview_comp),


    path('admin_reply/<str:id>',views.admin_reply),
    path('reply_post/',views.reply_post),
    path('viewdeliveryboy/',views.viewdelivery),
    path('feedback/',views.feed),
    path('feedbackpost/',views.feedpost),
    path('viewfeedback/',views.adminview_feedback),
    path('schedule/',views.shed),
    path('schedulepost/',views.shedpost),
    path('userviewshedule/<str:id>',views.viewsheduleuser),
    path('allocate/<str:id>',views.allocate),
    path('allocatepst/',views.allocatepost),
    path('viewallocate/',views.viewallocate),


    path('stock/',views.stoc),
    path('stockpost/',views.stocpost),
    path('stockview/',views.stockview),
    path('stedit/<str:id>',views.stedit),
    path('stockedit/',views.stockedit),
    path('payment/<total>',views.pay),
    path('paymentpost/',views.paypost),
    path('shopvieworder/',views.shop_view_order),
    path('more/<str:id>',views.more),
    path('usermore/<str:id>', views.usermore),

    path('userdocview/',views.userdocview),
    path('boyboyview/', views.boyboyview),
    path('uservieworder/',views.user_view_order),
    path('appoiment/<str:id>',views.appoiment),
    path('viewsheduledoc/',views.viewsheduledoc),
    path('viewapp/',views.viewapp),
    path('pres/<str:id>',views.pres),
    path('prespost/',views.Prescripton),
    path('viewpres/<str:id>',views.viewpres),
    path('viewpresuser/<str:id>',views.viewpresuser),
    path('delivery_ordered/<str:id>',views. delivery_ordered),
    path('logout/',views.logout),

]
